CPSC 321 Shawn Bowers

Office Hours: Tu/Th 12:30-1:30
wed 1-3
or by email appointment

Course Topics: 
    * Relational model
    * Basic and Interm SQL ( in mySQL )
    * Logical database design
        - ER model, normalization
    * Physical database design, centered around optimization
    * Transactions and Recovery

1. Persistance
    * Data that lives longer than the application, can access it after turning application off

2. Database
    * Data store + organization/structure

3. Database management system ( DBms )

4. DBms suported user operations
    * design an organization for data ( "schema" )
    * update data by adding, modifying or deleting
    * retrieve data ( via a "query language" )
    * manage who has access to what data

5. Relational Database management system ( RDBms )
    * all data is stored in relation model ( tables made of rows/cols )
    * SQL is typical language to interact with RDBms

6. SQL command (sub) languages
    * Data definition language ( DDL )
        - create, alter, drop
    * Data manipulation language ( DML )
        - insert, update, delete
    * Data Query Lang. ( DQL )
        - Select , with
    * Data Control Language ( DCL )
        - grant and revoke permissions

7. Transaction processing ( OLTP )
    * support "Daily operations" of a business
        - modifying, adding ,removing ... "write heavy"
        - some querying
        - fast response times many concurrent sessions

8. Analytics ( OLAP )
    * supports 'decision making' tasks of business
    * queries often complicatied, involve large amounts of data
        - read heavy workloa

9. Transactional concurrency
    * challenging

10. ACID propers ( transaction concurrency )
    A: atomicity - all or nothing
    C: consistency - transactions preserve DB constraints
    I: isolation - transactions execute as if there aren't others (serializability)
    D: durability - transaction effect not lost


DB for e-bike company:
    - GBFS = General Bikeshare Feed Specification
        * types of vehicles
        * real-time info
        * customer data

Relation (table) (schema + instance): 
Vehicle-Type            | relation
    V_type make model   | schema
    1      segway nine V  ( Relation instance)
...

*
Relation "Schema"
    * relation name ( Vehicle type)
    * set of attributes
        - each has name
        - domain
            + a domain is both: 
                a data type (storage type) both collection and storage types are "first normal form"
                    > we assume "atomic" data types eg. int, string,bool; list,set (collection types)
                set of allowable values ( opt. constraint) like age should be between 1-120 roughly


 Syntax to refer to schema: R(a1:int,a2:string..an) can void types
    - Vehicle-type(V_type make model)

Relation "Instance"
    * a set of "tuples" ("row", "record")
        - order doesn't matter, no repeat data
    * many possible instances of a schema

A "database schema" is a set of relations schemas ( tables )
A "database instance" is the set of its relation instances

Arity (degree) = # of cols

Cardinality = number of rows

NULL is a special value 
    * means "unknown" or "N/A"

A "key" is an attribute, or a set of attribues (composite key), with unique values
    - ex. ID

*** Q: What are the potential keys?

    VehicleType(vt_id *, make, model)
    Vehicle(v_id *, vt_id, lat, lon)
    Trip(v_id * , c_id*, startDate*, startTime*, totalCharge)

    Customer(c_id, email, ssn, ...)
        * each individually are "candidate keys"
        * minimal candidate keys have been narrowed down to the smallest they can be

Primary Key
    * key(unqiue) + storage ( no Nulls)


"Bad" references = a keys which reference another table where the instance does not exist

We can prevent bad references by using "foreign keys"
    * States that column values in one table must come from a key in another table
        ex. v_id must be a number exisiting in an alternate table
    * requires vehicle rows to refer to vehicleType rows ( or to be NULL )

Enforcing foriegn key constraints is known as "referential integrity"

VehicleType(vt_id,make,model,default_plan)
Vehicle(v_id,make,model,lat,lon)
PricingPlan(p_id,price-per-min,unlock_price)
AllowedPlan(vt_id,p_id)

1.  Vehicle.vt_id references VehicleType.vt_id
2.  VehicleType.default-plan references PricingPlan.p_id
3.  AllowedPlan.vt_id references VehicleType.vt_id
4.  AllowedPlan.p_id references pricingplan.p_id
    * VehicleType.(vt_id,default_plan) references AllowedPlans.(vt_id,p_id)
        ex. ^^^ This is a composite foreign key ( order matters of parameters )

Foreign Key summary:
    * Must reference the entire primary key
        - if R(_x,_y,z), S(_u,x,y)
        then, S.(x,y) references R.(x,y)
    * Must have null or matching fk value
    * enforced by DBms
    * Can be NULL

 Q: What do the following key constraints imply?
    
    1. AllowedPlan(vt_id_, p_id_)
        * implies that every price plan can have any vehicle type

    2. AllowedPlan(vt_id_, p_id)
        * Each vehicle type can have at most 1 allowed pricing plan
    3. AllowedPlan(vt_id, p_id_)
        * For every pricing plan, only one vehicle type can have it 

Domains, PKs (candidate keys), Fks are types of "integrity constraints"

Surrogate keys and Artificial keys:
    usually we have "natural" keys
        - when composite can make Fks problematic
Artificial ex.

R(x1,x2,x3,x4) => S(y1,y2,y3, x1.,x2.,x3.,x4.) 
instead: 
R(x1,x2,x3,x4,z1) => S(y1,y2,y3, z1.) Artificial keys are not "naturally occurring"

Surrogate Keys are managed by the DB to create unique values for the key
    * Can cause rows with duplicate values

Schema Diagram Basics:
    1. Ea. table drawn as a labaled box

 Branch 
| brand_name PK | Address | phone |
| --------------| ------- | ----- |

Copy
| barcode PK | 
| ---------- |

Account
| Acct_id PK | acct_ name | FK main_ branch | 
| ---------- | ---------- | --------------- | 


Loan
| acct_id PK FK_1 | barcode PK FK_2 | checkout_date PK | due_Date | return_date |
| --------------- | --------------- | ---------------- | -------- | ----------- | 

( so a person can checkout the same book multiple times)

SQL: Structured Query language (declarative language)
- 1999 SQL 3
- SQL is mostly case insensitive
- convention is commands are all uppercase
- remember to add drop command at start of sql files (DROP TABLE IF EXISTS tablename;)

Imperative languages: tells computer how and what you want to do
Declarative (SQL): tell it what a solution should look like, what not how;  command based

#### Connecting to mySQL (Running Maria DB 10.3)
1. DB-server ( cps-database.gonzaga.edu)
1. mysql -p -h cps-database (mysql -u username -p -h cps-database )
    - (login with a password, and specifying the host)
    - If you are off campus use the gonzaga vpn to access 
    - ada.gonzaga.edu
1. ssh in terminal on local machine to get to ada
    - can by-pass ada entirely by installing a mysql client on local machine
Once inside the Database
1. use mmanca2_DB;

table syntax:
CREATE TABLE tablename(
    att1 type1 (can add aditional constraints here),
    att2 type2, ...
    attn typen,
);
cmmds
- explain tablename;
- show tables;


Query commands:
SELECT * FROM tablename;
INSERT INTO tablename VALUES(v1,v2,...), $()_n$;

DROP TABLE tablename; (delete)
SOURCE filename;

##### 1. Integer values
- INT = 4 bytes
- MEDIUM INT = 3 bytes (not sql)
- SMALL INT = 2 bytes
- TINY INT = 1 byte
- BIG INT = 8 bytes
    - attributeName INT unsigned
- INT(size)

##### 2. Floating point values ( approximations, not good for precision )
- FLOAT
- DOUBLE
- FLOAT (M,D)
    - M = total digits, D = # of digits in M after decimal point
- DECIMAL (M,D) (for exact values)
    - DECIMAL (8,6) _ _. _ _ _ _ _ _

##### 3. Boolean/Binary values
- BOOL,BOOLEAN has false and true
- BIT(m)
    - ex. BIT(2) = 00, 01, 10, 11
##### 4. String values
- CHAR(N) where 0 <= N <= 255 ( fixed size )
- VARCHAR(N) where 0 <= N <= 65,535 ( variable size alocation)
    - more compact
- ENUM ('blue','green','red') specify all string values that can be entered
- BLOB = "Binary Large Object", allows to store as much data as DB can hold like an image
    - TEXT = Character version of a blob 
    - TINYTEXT supports up to 255 characters

##### 5. Date and Time Values
- YEAR = 'YYYY'
- DATE = 'YYYY:MM:DD'
- TIME = 'HH:MM' or 'HH:MM:SS'
- ** DATETIME = 'YYYY:MM:DD HH:MM:SS'

#### Creating Tables SQL
branch(branch_name PK,address,phone)
account(acct_id PK,acct_name,main_branch FK)

Foreign key format: FOREIGN KEY(att1,att2) REFERENCES branch_name(att1,att2)

CREATE TABLE branch (
    branch_name VARCHAR(50),
    address TINYTEXT NOT NULL,
    phone char(12) NOT NULL,
    PRIMARY KEY (branch_name)
    UNIQUE (address),
    UNIQUE(phone)
);

CREATE TABLE account(
    acct_id INT UNSIGNED,
    acct_name TINYTEXT NOT NULL,
    main_branch VARCHAR(50),
    <!-- Need this data type to be the same as branch_name because it is a FK -->
    PRIMARY KEY (acct_id),
    FOREIGN KEY (main_branch)
    REFERENCES branch(branch_name)
);

NOT NULL
    "attribute level constraint" 
    "attribute is required" vs. optional
UNIQUE
    "requires things to be unique"
CHECK
    "table level constraint"

#### Inserting Tables SQL
* Best to insert in large sums (called batching avoid overhead)
1. INSERT INTO tablename VALUES 
(v1,v2), (v1,v2);

2. INSERT INTO tablename (a1,a2) VALUES 
    (v1,v2),...;

3. INSERT INTO tablename SET 
    (a1 = v1), (a2 = v2)...; 
    <!-- can only change one row -->

##### DROP TABLE...
* remove all rows but keep the schema
    * DELETE FROM account;
* remove some rows
    * DELETE FROM account WHERE acct_id = 101;

##### Update 
* update attribute values of all rows
    * UPDATE account set main_branch = 'shadle';
* specific rows
    * UPDATE account set main_branch = 'shadle' WHERE acct_id = '101'

##### AUTO_INCREMENT for surrogates
CREATE TABLE pet(
    pet_id INT UNSIGNED AUTO_INCREMENT,
    pet_name TINYTEXT NOT NULL,
    pet_type TINYTYEXT NOT NULL DEFAULT 'dog',
    PRIMARY KEY(pet_id)
);

INSERT INTO pet(pet_name,pet_type) VALUES ('bill',cat');
<!-- pet_id is auto increment -->
INSERT INTO pet(pet_name) VALUES ('fido');
<!-- Uses auto increment and default value for dog -->

#### Boolean constraints using CHECK

Table level constraint 

CREATE TABLE loan(
    acct_id INT UNSIGNED,
    barcode INT UNSIGNED,
    Checkout_date DATE,
    due_date DATE NOT NULL,
    return_date DATE,
    PK(acct_id, barcode,Checkout_date),
    FK(acct_id) REFERENCES account(acct_id),
    CONSTRAINT valid_due_date CHECK ( checkout_date < return_date),
    CONSTRAINT valid_return_date CHECK ( return_date > checkout_date);
    
)